### ISSUE TITLE
Returns an error if context does not have a query param

### ISSUE THREAD

**Issue by kagof** [auth0-extensions/auth0-account-link-extension#10]
In the account link rule, trying to read from the `query` param results in:

`ERROR: Cannot read property 'link_account_token' of undefined`

**Steps to reproduce:**
call this rule with a context which does not include a `query` param. This can happen when calling the `/oauth/token` endpoint to log in.

**Workaround:**

at the beginning of the rule include the line:

`if (!context.request.query) context.request.query = {};`

**Comment by machuga** [comment]
Patched! This should roll out to the gallery by mid-tomorrow.
