### ISSUE TITLE
Account linking always results in a "Oops something went wrong" if redirect_uri contains #

### ISSUE THREAD

**Issue by jtaylor10** [auth0-extensions/auth0-account-link-extension#14]
Dug into the code and found it encodes the query string params when calling `authorize` using `encodeURI` but this is not sufficient for query params. For query params you must use `encodeURIComponent` instead which handles `#, @, &, ?, /, =, etc`

**Comment by machuga** [comment]
Thanks for pointing it out! We'll get on it 👍

**Comment by francocorreasosa** [comment]
I'll take this one! Thanks!

**Comment by machuga** [comment]
Patched! This should roll out to the gallery by mid-tomorrow.

**Comment by jtaylor10** [comment]
Great news! thanks for the fast action taken. Just to clarify, does "roll out to the gallery" mean roll out to auth0 accounts using this extension or something else? Will we have to do anything to pick up these patches in auth0 once this is pushed out?

**Comment by francocorreasosa** [comment]
It means that you will be able to go to the Extension Gallery in your Management Dashboard and update the extension to get these patches. 😄
