### ISSUE TITLE
opaque access_token returned (expecting JWT)

### ISSUE THREAD

**Issue by stevezau** [auth0-extensions/auth0-account-link-extension#34]
When using the account linking extension it seems the access_token returned to the application is an opaque value rather than a JWT. 

I'm not sure what's going on, still trying to t-shoot, will update this ticket

**Comment by francocorreasosa** [comment]
I'm not sure what may be happening here, since in case the user wants to link accounts, we use the same `response_type` that cames from the first request. In case the user wants to skip the linking process, we just call `/continue?state={state}`

**Comment by francocorreasosa** [comment]
@stevezau what `response_type` did you used when trying to authorize?

**Comment by stevezau** [comment]
Hi,

It seems to happen ONLY when I first sign up with a DB user, then log in via a social account. Account link ext kicks in, asks me to verify my DB user/pass then the access_token returned is not a JWT.

I've attached the HAR [www.newszero.info.har.zip](https://github.com/auth0-extensions/auth0-account-link-extension/files/1641336/www.newszero.info.har.zip)
