### ISSUE TITLE
Link is not happening

### ISSUE THREAD

**Issue by rstcruzo** [auth0-extensions/auth0-account-link-extension#44]
I'm using this plugin and I can't get it to work. It prompts to login the previously created account but it doesn't link the accounts after a successful login, I can still see both users on Auth0 dashboard. On android logcat I get this error:

`E/OAuthManager: Error, access denied. Check that the required Permissions are granted and that the Application has this Connection configured in Auth0 Dashboard.`

On Auth0 Dashboard Logs I get Failed Login on my main client, not on the client that this extension creates. Any suggestion?

The previously created account is Auth0's and the new one is a social account (tried Google and Facebook). I'm using WebAuthProvider to login social accounts. I tried to verify the email first, still not working.

**Comment by machuga** [comment]
Hi @rstcruzo!

Sorry to hear you're having issues. Are you by chance using the standard developer credentials (api keys) rather than your own credentials for Google? There is an issue with using Google's social login when linking accounts unless you've entered your own api keys.

**Comment by rstcruzo** [comment]
HI @machuga. Well I tried with Facebook and I get the same error message plus no linking. The issue might be something else.

**Comment by machuga** [comment]
We're not having luck replicating the issue here, but we're going to try a few different ideas.

**Comment by rstcruzo** [comment]
Any permission, grant type or scope I may be missing?

**Comment by francocorreasosa** [comment]
Hi @rstcruzo. I'm trying with a fresh tenant with the extension installed and this sample app https://github.com/auth0-extensions/auth0-account-link-extension/tree/master/sample-app

I can't reproduce the issue. Are you using a hosted login page? Can you tell us a little bit more about your authorization settings?

**Comment by rstcruzo** [comment]
No hosted login page. I'm not really sure which settings you may have interest in. 
- OIDC Conformant is enabled
- JWT
- Password grant types enabled for main client
- Main client type is native
- Extension client is native, oidc disabled, default grant types
- Only extension rule is active

**Comment by francocorreasosa** [comment]
Did you enable the social connections for the `auth0-account-link` client? You can manage that in https://manage.auth0.com/#/connections/social clicking in the connection and going to the tab "Clients".

**Comment by rstcruzo** [comment]
They are enabled by default.

**Comment by rstcruzo** [comment]
I got another error in Log of the main client.

Type: Failed Exchange
Description: Grant type 'client_credentials' not allowed for the client.

But if I enable client_credentials in my main client I get asked to change the client type to Native in the logcat (Android). Therefore disabling client_credentials.

**Comment by francocorreasosa** [comment]
Hmm. Just tried to use a Native Client (Android as well) and could login and link account without any  problem. (using web flow). I'm going to try with Lock, but I should have the same result.

**Comment by rstcruzo** [comment]
This is the error I get when I enable client_credentials in the main client:

`E/PKCE: Please go to 'https://manage.auth0.com/#/applications/bxpBn4TTOVzHKuDWIxwdvUClCjiucnM3/settings' and set 'Client Type' to 'Native' to enable PKCE.`

**Comment by rstcruzo** [comment]
This is the error I get when I enable client_credentials:

`E/PKCE: Please go to 'https://manage.auth0.com/#/applications/CLIENT_ID/settings' and set 'Client Type' to 'Native' to enable PKCE.`

**Comment by machuga** [comment]
@rstcruzo Out of curiosity, have you changed the client that is used by the account link extension? The one it creates is the one that should be used for that process, but your own clients can be used for the main authentication portion.

**Comment by rstcruzo** [comment]
No, I didn't. Is there anything the extension needs enabled to work?

**Comment by rstcruzo** [comment]
I think it may has something to do with permissions of the extension or the client. The process manages to create the second account and registers another login for the first account (requested by the extension). So the only missing part is the linking; besides, the error is about permissions. This is why I am asking, which permissions or scopes does the extension (or client) needs?

**Comment by rstcruzo** [comment]
@machuga @francocorreasosa ok, I debugged the rule, this is the error I get

`3:49:19 PM: [ACCOUNT_LINK]:  Entered Account Link Rule3:49:19 PM: [ACCOUNT_LINK]:  API call failed:  { statusCode: 401,
  error: 'Unauthorized',
  message: 'Invalid token',
  attributes: { error: 'Invalid token' } }3:49:19 PM: [ACCOUNT_LINK]:  [object Object] Error: [object Object]
    at Request.handleResponse [as _callback] (/data/io/60b0bf8419474fcca625044ca65b6555/webtask.js:261:18)
    at Request.self.callback (/data/_verquire/request/2.56.0/node_modules/request/request.js:354:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1207:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1153:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickDomainCallback (node.js:466:17)`

**Comment by Niclas1976** [comment]
Hello. I get this error, and the "other" user is created as a separate user in auth0.

```
invalid_request: Invalid parameter: client_id must be a string
VIEW LOG TRACKING ID: 92ff0974b5b146720da6 
```
