### ISSUE TITLE
Do not allow skipping link

### ISSUE THREAD

**Issue by MrBlaise** [auth0-extensions/auth0-account-link-extension#54]
Hi,

Is there a way to force users to link accounts? In my scenario, the user is identified by his or her email in the database, if he or she has multiple login options it is fine, but creating different users in auth0 with the same email will break my system because there will be two users with same email addresses.

If I could force users to link their account if they use the same email address this would be solved I think.

**Comment by apelliciari** [comment]
up, please give us this possibility

**Comment by machuga** [comment]
Hello @apelliciari and and @MrBlaise - have you tried to use the pre-existing Rules for this scenario? The extension is an adaptation of that to provide the opt-in prompt.

**Comment by apelliciari** [comment]
sorry @machuga for the late feedback, yes we've solved it using the pre-existing rule, and skipping the extension.
The problem we had was related to the email verification: because in our logic email are not verified, it wasn't linking the accounts

Thanks for the answer

**Comment by adomokos** [comment]
I might be late for this party, but we are facing the same scenario as well. What pre-existing rule are you mentioning in this thread?

**Comment by saltukalakus** [comment]
It is the deprecated rule what Matt refers to by pre-existing rule. That rule isn't recommended anymore for new designs as it links accounts just by looking at the email verification status of the users. In contrast, the account linking extension links accounts after the user logs in on both accounts. You may leave a feedback at https://auth0.com/feedback for an option to force the accounts to link with the extension.

**Comment by ADTC** [comment]
Any native solution for this?

I found a workaround, which is to use CSS to hide it. (Note: It's only a cosmetic change, and if someone really wants to, they can inspect the DOM and show it again. So it doesn't disable the ability to skip linking entirely.)

The easiest way will be to just add a style tag in the extension settings, custom HTML box:

<img width="859" alt="image" src="https://github.com/auth0-extensions/auth0-account-link-extension/assets/6047296/da047ca0-9840-4f93-bd09-15916be0b6ce">

This is the CSS to insert after `{{ CustomCSS }}`:

```html
    <style>
      p.auth0-lock-alternative {
        display: none !important;
      }
    </style>
```


Or you can put the CSS in the self-hosted Custom CSS file which you linked to the extension when installing it. (I can't find a way to do this linkage once the extension is already installed.)

Or if you really want to, use JavaScript in `<script>` tag to nuke that element from the DOM. I leave this as an exercise to you, but if you do it this way, I appreciate if you can please share your code. Thank you.

**Comment by ADTC** [comment]
Note that you may need to do additional modifications as described here: https://community.auth0.com/t/account-linking-skip-option/63675
