### ISSUE TITLE
Bug with setting custom css

### ISSUE THREAD

**Issue by mathiasconradt** [auth0-extensions/auth0-account-link-extension#75]
Setting a custom css path in the extension settings does not work properly. The user is supposed to enter an absolute URL, however, the rendered page takes it as a relative URL and puts a "https://cdn.auth0.com/extensions/auth0-account-link/assets/" in front of it.

<img width="726" alt="Screen Shot 2020-07-08 at 13 41 34" src="https://user-images.githubusercontent.com/295122/86914522-c7989000-c120-11ea-9c0c-b92a68604fb0.png">

<img width="1490" alt="Screen Shot 2020-07-08 at 13 41 27" src="https://user-images.githubusercontent.com/295122/86914567-d3845200-c120-11ea-9764-a0996588ce68.png">

**Comment by bradleybuda** [comment]
I'm also having this issue. Not sure I understand the bot's reply here - it's a bug that needs a reply from a maintainer.

**Comment by kierans** [comment]
I raised this in the forums https://community.auth0.com/t/problem-styling-auth0-account-link-extension/52609

**Comment by ademartini** [comment]
Thank you for reporting this Mathias.  We are now tracking this issue internally.

**Comment by kierans** [comment]
@ademartini It's great that you're tracking it internally, however by closing this ticket if someone else is to come along with the same problem, how are they going to know the progress of any fix? Closing public tickets really leaves people in the dark.

IMO these issues should remain open until a fix is actually deployed.

**Comment by adomokos** [comment]
I've bumped into the same issue.

**Comment by nikolap** [comment]
Same issue here, even though this ticket is closed it remains a bug

**Comment by adomokos** [comment]
I submitted a ticket to Auth0 about this. This is the response I got:

> Thank you for contacting Auth0 Support. I'll create a ticket with the Engineering team to try and expedite the fix for the CSS option issue.

**Comment by madsharm** [comment]
The issue should be fixed in latest version of extension 2.6.4 , feel free to give it a try. Let us know in case you face any problems.
