### ISSUE TITLE
user rule config instead of writing credentials into the source code of the rule

### ISSUE THREAD

**Issue by gagalago** [auth0-extensions/auth0-account-link-extension#77]
I saw that credentials of the client id and client secret of the rule are written directly into the rule. isn't it possible to use instead the [config variable keys for rules](https://auth0.com/docs/api/management/v2#!/Rules_Configs/get_rules_configs)?
that can also solve [the issue of custom domain](https://auth0.com/docs/extensions/account-link#custom-domains) that need to be re-applied on each update of the extension.

are you open to that kind of change? if yes, do you have some advice to do it properly?

**Comment by gagalago** [comment]
yes, still relevant. I need a review of the pull request

**Comment by ademartini** [comment]
Hey @gagalago thank for the PR.  We are in the process of reviewing open PRs for this extension and will reach out to you on the PR itself.

**Comment by ademartini** [comment]
Let's continue the conversation on the PR itself and close this issue.
