### ISSUE TITLE
Changing locales overwrites customization to widget settings and vice versa

### ISSUE THREAD

**Issue by jimwheaton** [auth0-extensions/auth0-account-link-extension#91]
### Description

Running into an issue trying to change the messaging in `locales`. If I customize the text in `locales`, it overwrites any customization I’ve done in the widget settings screen. When I then update the widget settings to add my customization back, the locales are reset to their default values, overwriting my customization.

### Steps to reproduce
1. customize something on the `Widget Settings` screen, such as the color and click `Save Changes`
![image](https://user-images.githubusercontent.com/1443842/94864010-31f36080-03f0-11eb-8ec3-7ad631a51dcc.png)
2. click on `Manage Locales` in the top right menu, then customize any of the fields and click `Save Changes`
![image](https://user-images.githubusercontent.com/1443842/94864185-7979ec80-03f0-11eb-9cbc-71be0656495b.png)
3. go back to the `Widget Settings` screen and notice that your customizations have been overwritten
4. add your customizations back to the `Widget Settings` screen and click `Save Changes`
5. click on `Manage Locales` and note that your customization is lost

### Expected behavior
Customizations should persist on both the `Widget Settings` and `Locales` screens

**Comment by ademartini** [comment]
Hey Jim, thank you for reporting this bug.  While we are unable to give an exact timeline for this being fixed,  we have opened an internal ticket to prioritize and track this issue.
