### ISSUE TITLE
No support for ADFS?

### ISSUE THREAD

**Issue by msuiche** [auth0-extensions/auth0-account-link-extension#92]
Let's say if a user email `foo@bar.com` has an ADFS provider which comes from the internal `xxxxxxxxx.com` and then they migrate their ADFS to `yyyyyyyy.com` the user now has two identifiers but the email address is still the same `foo@bar.com` - they should be linked/merged - but this is not the case.

adfs|xxxx-adfs-sso|aaaaaaaaaaa@xxxxxxxxx.com 
adfs|xxxx-adfs-sso|aaaaaaaaaaa@yyyyyyyy.com

**Comment by ademartini** [comment]
Hi Matt thank you for the feedback. We see that a support ticket was filed for this issue.  A suggestion was made to utilize the Management API as a workaround.  Feel free to reach out via the support center if you have any further issues with this extension.
