### ISSUE TITLE
Enable account selection when linking accounts

### ISSUE THREAD

**Issue by mmaddex** [auth0-extensions/auth0-account-link-extension#94]
### Steps to reproduce
1. Create a Google Social Connection ("user@gmail.com") user in Auth0 tenant 
2. Log "user@gmail.com" out of google, log back into google with another account ("another_user@gmail.com")
3. Sign up/log in to Auth0 tenant with a Database connection using "user@gmail.com"

**Expected**: I am prompted to select the correct google account to use for account linking

**Actual**: The account linking extension attempts to use the logged in google account ("another_user@gmail.com") to link with the "user@gmail.com" Database connection, resulting in an error.

### Current workaround
It is possible to address this issue by always sending `prompt=select_account` to Google using a static `upstream_params` connection option.

### Workaround gap
This makes for a sub-optimal log experience for every other interaction with Goolge since the user is always prompted to select an account. Ideally, we would be able to target only the account linking flow with `prompt=select_account`.

### Potential solution

It seems to me if we added `prompt=select_account` to the `/authorize` request required for account linking:
https://github.com/auth0-extensions/auth0-account-link-extension/blob/00eeeb2c9d908eb85704977f97f09ed03de5edcb/public/index.js#L44-L56
customers could then choose to leverage that param using dynamic `upstream_params`. If no `upstream_params` are set this would just be ignored and everything would function as it does today.

**Comment by ademartini** [comment]
We have moved this to an internal JIRA ticket on the backlog.
